import ImagesIcon from "@sanity/icons/Images";
import { defineArrayMember, defineField, defineType } from "sanity";

export const artwork = defineType({
  name: "artwork",
  title: "Artwork",
  type: "document",
  icon: ImagesIcon,
  groups: [
    { name: "essential", title: "Artwork details", default: true },
    { name: "sales", title: "Availability & purchase" },
    { name: "display", title: "Website display" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "essential",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Website address",
      type: "slug",
      group: "essential",
      options: { source: "title", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "mainImage",
      title: "Main image",
      description: "The image shown in the gallery grid.",
      type: "contentImage",
      group: "essential",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "detailImages",
      title: "Detail and close-up images",
      description:
        "Drag to reorder. These appear below the main image on the artwork page.",
      type: "array",
      group: "essential",
      of: [defineArrayMember({ type: "contentImage" })],
    }),
    defineField({
      name: "medium",
      title: "Medium",
      type: "string",
      group: "essential",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "dimensions",
      title: "Dimensions",
      type: "string",
      group: "essential",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "depth",
      title: "Depth / edge details",
      type: "string",
      group: "essential",
    }),
    defineField({
      name: "year",
      title: "Year",
      type: "string",
      group: "essential",
    }),
    defineField({
      name: "description",
      title: "Description",
      type: "text",
      rows: 8,
      group: "essential",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "collections",
      title: "Collections / series",
      type: "array",
      group: "essential",
      of: [
        defineArrayMember({ type: "reference", to: [{ type: "collection" }] }),
      ],
    }),
    defineField({
      name: "availability",
      title: "Availability",
      type: "string",
      group: "sales",
      initialValue: "available",
      options: {
        layout: "radio",
        list: [
          { title: "Available", value: "available" },
          { title: "Reserved", value: "reserved" },
          { title: "Sold", value: "sold" },
          { title: "Not for sale", value: "not-for-sale" },
        ],
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "price",
      title: "Price in US dollars",
      type: "number",
      group: "sales",
      validation: (rule) => rule.positive(),
    }),
    defineField({
      name: "showPrice",
      title: "Show price on the website",
      type: "boolean",
      group: "sales",
      initialValue: false,
      hidden: ({ parent }) => typeof parent?.price !== "number",
    }),
    defineField({
      name: "galleryName",
      title: "Gallery or seller name",
      type: "string",
      group: "sales",
    }),
    defineField({
      name: "purchaseUrl",
      title: "Purchase page link",
      description: "Paste the full Orleans Gallery or other gallery URL.",
      type: "url",
      group: "sales",
      validation: (rule) => rule.uri({ scheme: ["http", "https"] }),
    }),
    defineField({
      name: "purchaseButtonLabel",
      title: "Purchase button text",
      type: "string",
      group: "sales",
      placeholder: "Purchase at Orleans Gallery",
    }),
    defineField({
      name: "certificateNote",
      title: "Certificate / authenticity note",
      type: "string",
      group: "sales",
    }),
    defineField({
      name: "featured",
      title: "Feature on the home page",
      type: "boolean",
      group: "display",
      initialValue: false,
    }),
    defineField({
      name: "displayOrder",
      title: "Display order",
      description: "Lower numbers appear first.",
      type: "number",
      group: "display",
      initialValue: 100,
    }),
    defineField({
      name: "isVisible",
      title: "Show on website",
      type: "boolean",
      group: "display",
      initialValue: true,
    }),
  ],
  orderings: [
    {
      title: "Website order",
      name: "displayOrder",
      by: [
        { field: "displayOrder", direction: "asc" },
        { field: "title", direction: "asc" },
      ],
    },
  ],
  preview: {
    select: {
      title: "title",
      media: "mainImage",
      availability: "availability",
    },
    prepare: ({ title, media, availability }) => ({
      title,
      media,
      subtitle: availability ? availability.replaceAll("-", " ") : "",
    }),
  },
});
